site_name: Q-Drives CANopen Documentation
nav:
  - Introduction: index.md
  - CANopen: canopen.md
  - Network Management: network-management.md
  - Operation Mode: operation-modes.md
  - Object Dictionary: object-dictionary.md
  - About: about.md
dev_addr: 127.0.0.1:9090
theme: readthedocs
extra_css:
  - css/custom.css